apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csye7125.fullname" . }}-app
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csye7125.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csye7125.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          env:
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}  