apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "csye7125.fullname" . }}-app
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "csye7125.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "csye7125.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          livenessProbe:
            exec:
              command:
                - /usr/local/bin/liveness-check.sh
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          readinessProbe:
            exec:
              command:
                - /usr/local/bin/readiness-check.sh
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
          env:
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}  