apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "csye7125.fullname" . }}-app
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.namespace }}
spec:
  template:
    metadata:
      labels:
        {{- include "csye7125.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: db-migration
          image: "{{ .Values.initContainer.image }}:{{ .Values.initContainer.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.initContainer.pullPolicy }}
          env:
            {{- range .Values.initContainer.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}-app
          image: "{{ .Values.app.image }}:{{ .Values.app.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.app.pullPolicy }}
          env:
            {{- range .Values.app.env }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{- end }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}  